package api

import (
	"Iltmw/model"
	"fmt"
	"testing"
)

func TestGetAns(t *testing.T) {
	ques := &model.ModelObj{
		PaperId: "OS6hpoUIRVM2BLDxVkX",
		Type:    "5",
		List: []model.ListItem{
			{
				PaperDetailId: "us7C9sNKOFy8unEe202",
				Title:         "culture",
				AnswerA:       "时尚",
				AnswerB:       "文化",
				AnswerC:       "狂热",
				AnswerD:       "品种",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe203",
				Title:         "today",
				AnswerA:       "今天",
				AnswerB:       "明天",
				AnswerC:       "昨天",
				AnswerD:       "明年",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe204",
				Title:         "tomorrow",
				AnswerA:       "今天",
				AnswerB:       "明天",
				AnswerC:       "昨天",
				AnswerD:       "明年",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe205",
				Title:         "beauty",
				AnswerA:       "美丽",
				AnswerB:       "丑陋",
				AnswerC:       "妈妈",
				AnswerD:       "丑",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe206",
				Title:         "charge",
				AnswerA:       "充电",
				AnswerB:       "收费",
				AnswerC:       "充值",
				AnswerD:       "充电器",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe207",
				Title:         "change",
				AnswerA:       "改变",
				AnswerB:       "变化",
				AnswerC:       "更换",
				AnswerD:       "变",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe208",
				Title:         "milk",
				AnswerA:       "牛奶",
				AnswerB:       "奶粉",
				AnswerC:       "奶酪",
				AnswerD:       "奶",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe209",
				Title:         "water",
				AnswerA:       "水",
				AnswerB:       "饮料",
				AnswerC:       "酒",
				AnswerD:       "饮水",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe210",
				Title:         "food",
				AnswerA:       "食物",
				AnswerB:       "饮食",
				AnswerC:       "食品",
				AnswerD:       "食",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe211",
				Title:         "drink",
				AnswerA:       "喝",
				AnswerB:       "饮料",
				AnswerC:       "饮品",
				AnswerD:       "饮",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe212",
				Title:         "language",
				AnswerA:       "语言",
				AnswerB:       "方言",
				AnswerC:       "文字",
				AnswerD:       "语言学",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe213",
				Title:         "school",
				AnswerA:       "学校",
				AnswerB:       "学院",
				AnswerC:       "学府",
				AnswerD:       "教育",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe214",
				Title:         "book",
				AnswerA:       "书",
				AnswerB:       "图书",
				AnswerC:       "教材",
				AnswerD:       "书籍",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe215",
				Title:         "weather",
				AnswerA:       "天气",
				AnswerB:       "气候",
				AnswerC:       "天候",
				AnswerD:       "天象",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe216",
				Title:         "science",
				AnswerA:       "科学",
				AnswerB:       "学科",
				AnswerC:       "技术",
				AnswerD:       "实验",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe217",
				Title:         "art",
				AnswerA:       "艺术",
				AnswerB:       "画作",
				AnswerC:       "作品",
				AnswerD:       "艺术品",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe218",
				Title:         "music",
				AnswerA:       "音乐",
				AnswerB:       "乐曲",
				AnswerC:       "歌曲",
				AnswerD:       "旋律",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe219",
				Title:         "movie",
				AnswerA:       "电影",
				AnswerB:       "影片",
				AnswerC:       "影像",
				AnswerD:       "影剧",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe220",
				Title:         "computer",
				AnswerA:       "计算机",
				AnswerB:       "电脑",
				AnswerC:       "主机",
				AnswerD:       "服务器",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe221",
				Title:         "internet",
				AnswerA:       "互联网",
				AnswerB:       "网络",
				AnswerC:       "网",
				AnswerD:       "因特网",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe222",
				Title:         "library",
				AnswerA:       "图书馆",
				AnswerB:       "书库",
				AnswerC:       "阅览室",
				AnswerD:       "资料室",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe223",
				Title:         "television",
				AnswerA:       "电视",
				AnswerB:       "电视机",
				AnswerC:       "电视节目",
				AnswerD:       "电视台",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe224",
				Title:         "radio",
				AnswerA:       "收音机",
				AnswerB:       "广播",
				AnswerC:       "电台",
				AnswerD:       "无线电",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe225",
				Title:         "phone",
				AnswerA:       "电话",
				AnswerB:       "手机",
				AnswerC:       "电话机",
				AnswerD:       "电话线",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe226",
				Title:         "bicycle",
				AnswerA:       "自行车",
				AnswerB:       "单车",
				AnswerC:       "脚踏车",
				AnswerD:       "骑行",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe227",
				Title:         "car",
				AnswerA:       "汽车",
				AnswerB:       "轿车",
				AnswerC:       "车",
				AnswerD:       "车辆",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe228",
				Title:         "plane",
				AnswerA:       "飞机",
				AnswerB:       "航班",
				AnswerC:       "飞行器",
				AnswerD:       "航机",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe229",
				Title:         "train",
				AnswerA:       "火车",
				AnswerB:       "列车",
				AnswerC:       "高铁",
				AnswerD:       "动车",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe230",
				Title:         "city",
				AnswerA:       "城市",
				AnswerB:       "都市",
				AnswerC:       "城镇",
				AnswerD:       "市区",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe231",
				Title:         "village",
				AnswerA:       "村庄",
				AnswerB:       "村落",
				AnswerC:       "乡村",
				AnswerD:       "村",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe232",
				Title:         "mountain",
				AnswerA:       "山",
				AnswerB:       "山脉",
				AnswerC:       "高山",
				AnswerD:       "山峰",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe233",
				Title:         "river",
				AnswerA:       "河流",
				AnswerB:       "江",
				AnswerC:       "溪流",
				AnswerD:       "河川",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe234",
				Title:         "ocean",
				AnswerA:       "海洋",
				AnswerB:       "大海",
				AnswerC:       "海",
				AnswerD:       "洋",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe235",
				Title:         "forest",
				AnswerA:       "森林",
				AnswerB:       "林地",
				AnswerC:       "丛林",
				AnswerD:       "树木",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe236",
				Title:         "desert",
				AnswerA:       "沙漠",
				AnswerB:       "荒漠",
				AnswerC:       "沙地",
				AnswerD:       "沙丘",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe237",
				Title:         "island",
				AnswerA:       "岛屿",
				AnswerB:       "岛",
				AnswerC:       "小岛",
				AnswerD:       "群岛",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe238",
				Title:         "rain",
				AnswerA:       "雨",
				AnswerB:       "雨水",
				AnswerC:       "降雨",
				AnswerD:       "小雨",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe239",
				Title:         "snow",
				AnswerA:       "雪",
				AnswerB:       "降雪",
				AnswerC:       "积雪",
				AnswerD:       "冰雪",
			}, {
				PaperDetailId: "us7C9sNKOFy8unEe240",
				Title:         "apple",
				AnswerA:       "苹果",
				AnswerB:       "水果",
				AnswerC:       "果实",
				AnswerD:       "果树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe241",
				Title:         "banana",
				AnswerA:       "香蕉",
				AnswerB:       "水果",
				AnswerC:       "热带水果",
				AnswerD:       "香蕉树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe242",
				Title:         "grape",
				AnswerA:       "葡萄",
				AnswerB:       "果实",
				AnswerC:       "水果",
				AnswerD:       "葡萄树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe243",
				Title:         "orange",
				AnswerA:       "橙子",
				AnswerB:       "柑橘",
				AnswerC:       "水果",
				AnswerD:       "橙树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe244",
				Title:         "pear",
				AnswerA:       "梨",
				AnswerB:       "水果",
				AnswerC:       "果实",
				AnswerD:       "梨树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe245",
				Title:         "peach",
				AnswerA:       "桃子",
				AnswerB:       "水果",
				AnswerC:       "果实",
				AnswerD:       "桃树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe246",
				Title:         "plum",
				AnswerA:       "李子",
				AnswerB:       "水果",
				AnswerC:       "果实",
				AnswerD:       "李树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe247",
				Title:         "cherry",
				AnswerA:       "樱桃",
				AnswerB:       "水果",
				AnswerC:       "果实",
				AnswerD:       "樱桃树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe248",
				Title:         "mango",
				AnswerA:       "芒果",
				AnswerB:       "热带水果",
				AnswerC:       "果实",
				AnswerD:       "芒果树",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe249",
				Title:         "strawberry",
				AnswerA:       "草莓",
				AnswerB:       "水果",
				AnswerC:       "果实",
				AnswerD:       "草莓植株",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe250",
				Title:         "dog",
				AnswerA:       "狗",
				AnswerB:       "宠物",
				AnswerC:       "犬",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe251",
				Title:         "cat",
				AnswerA:       "猫",
				AnswerB:       "宠物",
				AnswerC:       "猫科",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe252",
				Title:         "bird",
				AnswerA:       "鸟",
				AnswerB:       "飞禽",
				AnswerC:       "宠物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe253",
				Title:         "fish",
				AnswerA:       "鱼",
				AnswerB:       "水产",
				AnswerC:       "水生动物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe254",
				Title:         "horse",
				AnswerA:       "马",
				AnswerB:       "骑马",
				AnswerC:       "牲畜",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe255",
				Title:         "cow",
				AnswerA:       "牛",
				AnswerB:       "奶牛",
				AnswerC:       "牲畜",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe256",
				Title:         "sheep",
				AnswerA:       "羊",
				AnswerB:       "绵羊",
				AnswerC:       "牲畜",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe257",
				Title:         "goat",
				AnswerA:       "山羊",
				AnswerB:       "绵羊",
				AnswerC:       "牲畜",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe258",
				Title:         "pig",
				AnswerA:       "猪",
				AnswerB:       "牲畜",
				AnswerC:       "动物",
				AnswerD:       "家畜",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe259",
				Title:         "chicken",
				AnswerA:       "鸡",
				AnswerB:       "禽类",
				AnswerC:       "动物",
				AnswerD:       "家禽",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe260",
				Title:         "duck",
				AnswerA:       "鸭",
				AnswerB:       "禽类",
				AnswerC:       "动物",
				AnswerD:       "家禽",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe261",
				Title:         "geese",
				AnswerA:       "鹅",
				AnswerB:       "禽类",
				AnswerC:       "动物",
				AnswerD:       "家禽",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe262",
				Title:         "rabbit",
				AnswerA:       "兔",
				AnswerB:       "宠物",
				AnswerC:       "动物",
				AnswerD:       "家畜",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe263",
				Title:         "tiger",
				AnswerA:       "老虎",
				AnswerB:       "猛兽",
				AnswerC:       "动物",
				AnswerD:       "猫科",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe264",
				Title:         "lion",
				AnswerA:       "狮子",
				AnswerB:       "猛兽",
				AnswerC:       "动物",
				AnswerD:       "猫科",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe265",
				Title:         "elephant",
				AnswerA:       "大象",
				AnswerB:       "巨兽",
				AnswerC:       "动物",
				AnswerD:       "哺乳动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe266",
				Title:         "giraffe",
				AnswerA:       "长颈鹿",
				AnswerB:       "动物",
				AnswerC:       "巨兽",
				AnswerD:       "哺乳动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe267",
				Title:         "zebra",
				AnswerA:       "斑马",
				AnswerB:       "动物",
				AnswerC:       "野生动物",
				AnswerD:       "马",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe268",
				Title:         "deer",
				AnswerA:       "鹿",
				AnswerB:       "动物",
				AnswerC:       "野生动物",
				AnswerD:       "家畜",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe269",
				Title:         "bear",
				AnswerA:       "熊",
				AnswerB:       "猛兽",
				AnswerC:       "动物",
				AnswerD:       "哺乳动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe270",
				Title:         "wolf",
				AnswerA:       "狼",
				AnswerB:       "猛兽",
				AnswerC:       "动物",
				AnswerD:       "哺乳动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe271",
				Title:         "fox",
				AnswerA:       "狐狸",
				AnswerB:       "猛兽",
				AnswerC:       "动物",
				AnswerD:       "哺乳动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe272",
				Title:         "monkey",
				AnswerA:       "猴子",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe273",
				Title:         "kangaroo",
				AnswerA:       "袋鼠",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe274",
				Title:         "koala",
				AnswerA:       "考拉",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe275",
				Title:         "panda",
				AnswerA:       "熊猫",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe275",
				Title:         "panda",
				AnswerA:       "熊猫",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe276",
				Title:         "penguin",
				AnswerA:       "企鹅",
				AnswerB:       "动物",
				AnswerC:       "鸟类",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe277",
				Title:         "whale",
				AnswerA:       "鲸鱼",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "海洋生物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe278",
				Title:         "dolphin",
				AnswerA:       "海豚",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "海洋生物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe279",
				Title:         "shark",
				AnswerA:       "鲨鱼",
				AnswerB:       "鱼类",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe280",
				Title:         "octopus",
				AnswerA:       "章鱼",
				AnswerB:       "软体动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe281",
				Title:         "crab",
				AnswerA:       "螃蟹",
				AnswerB:       "甲壳动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe282",
				Title:         "lobster",
				AnswerA:       "龙虾",
				AnswerB:       "甲壳动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe283",
				Title:         "jellyfish",
				AnswerA:       "水母",
				AnswerB:       "海洋生物",
				AnswerC:       "腔肠动物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe284",
				Title:         "starfish",
				AnswerA:       "海星",
				AnswerB:       "棘皮动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe285",
				Title:         "coral",
				AnswerA:       "珊瑚",
				AnswerB:       "腔肠动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe286",
				Title:         "snail",
				AnswerA:       "蜗牛",
				AnswerB:       "软体动物",
				AnswerC:       "陆生动物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe287",
				Title:         "frog",
				AnswerA:       "青蛙",
				AnswerB:       "两栖动物",
				AnswerC:       "动物",
				AnswerD:       "爬行动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe288",
				Title:         "snake",
				AnswerA:       "蛇",
				AnswerB:       "爬行动物",
				AnswerC:       "动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe289",
				Title:         "lizard",
				AnswerA:       "蜥蜴",
				AnswerB:       "爬行动物",
				AnswerC:       "动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe290",
				Title:         "panda",
				AnswerA:       "熊猫",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe291",
				Title:         "penguin",
				AnswerA:       "企鹅",
				AnswerB:       "动物",
				AnswerC:       "鸟类",
				AnswerD:       "野生动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe292",
				Title:         "whale",
				AnswerA:       "鲸鱼",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "海洋生物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe293",
				Title:         "dolphin",
				AnswerA:       "海豚",
				AnswerB:       "动物",
				AnswerC:       "哺乳动物",
				AnswerD:       "海洋生物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe294",
				Title:         "shark",
				AnswerA:       "鲨鱼",
				AnswerB:       "鱼类",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe295",
				Title:         "octopus",
				AnswerA:       "章鱼",
				AnswerB:       "软体动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe296",
				Title:         "crab",
				AnswerA:       "螃蟹",
				AnswerB:       "甲壳动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe297",
				Title:         "lobster",
				AnswerA:       "龙虾",
				AnswerB:       "甲壳动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe298",
				Title:         "jellyfish",
				AnswerA:       "水母",
				AnswerB:       "海洋生物",
				AnswerC:       "腔肠动物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe299",
				Title:         "starfish",
				AnswerA:       "海星",
				AnswerB:       "棘皮动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			{
				PaperDetailId: "us7C9sNKOFy8unEe300",
				Title:         "coral",
				AnswerA:       "珊瑚",
				AnswerB:       "腔肠动物",
				AnswerC:       "海洋生物",
				AnswerD:       "动物",
			},
			//{
			//	PaperDetailId: "us7C9sNKOFy8unEe301",
			//	Title:         "snail",
			//	AnswerA:       "蜗牛",
			//	AnswerB:       "软体动物",
			//	AnswerC:       "陆生动物",
			//	AnswerD:       "动物",
			//},
			//{
			//	PaperDetailId: "us7C9sNKOFy8unEe302",
			//	Title:         "frog",
			//	AnswerA:       "青蛙",
			//	AnswerB:       "两栖动物",
			//	AnswerC:       "动物",
			//	AnswerD:       "爬行动物",
			//},
		},
	}
	res, err := GetAns(ques)
	if err != nil {
		t.Error(err)
	}

	fmt.Println(*res)
}

func TestGetToken(t *testing.T) {
	token, err := GetToken(apiKey, secretKey)
	if err != nil {
		t.Error(err)
	}
	fmt.Println(token.AccessToken)
	//t.Log(token)
}
